### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#1]
For discussion about the tech stack related to the project "Commons" 🎉 

Currently the discussed tech stack is:
- React
- Node (Express)
- MongoDB for database - Although potential not for first sprint? To be discussed! See Kristina's comment below
- Jest for testing
- Styled Components for styling

(last edited 6:30pm 12.4.19)

**Comment by Oliversw** [comment]
In the past we have worked with issue labels from DWYL. We have copied them to this organization and propose using them in our project if you would agree. Here are the guidelines for them:

Clicking on a label will take you to an issue with further discussion on its existence and meaning:

- [`awaiting-review`](https://github.com/dwyl/labels/issues/49) #f39c12 - added to _issue_ once a PR with its resolution has been assigned to a reviewer (replaces `in-progress`)
- [`chore`](https://github.com/dwyl/labels/issues/37) #3A2716 - routine tasks that must be done for every project but require little active brain power
- [`discuss`](https://github.com/dwyl/labels/issues/8) #60EEEE - invites discussion from contributors
- [`epic`](https://github.com/dwyl/labels/issues/35) #000059 - big issues that span multiple days & need to be broken down
- [`external-dependency`](https://github.com/dwyl/labels/issues/54) #e6e6e6 - no further work can be carried out until a third party completes an action (specified in a comment in the issue)
- `in-progress` #009688 - added when you *start* working on an issue (and have assigned it to yourself)
- [`in-review`](https://github.com/dwyl/labels/issues/48) #128A0C - added to _PR_ by QA/reviewer to show a review is *in progress*
- [`merge-conflicts`](https://github.com/dwyl/labels/issues/26) #E74C3C - added to a _PR_ when it has merge conflicts that need to be fixed by the PR's creator
- [`please-test`](https://github.com/dwyl/labels/issues/46) #08E700 - added after PR is merged *and* the feature/fix/change has been deployed to *somewhere the Product Owner can actually **test** it* (assign issue to PO)
- `priority-1` #0D47A1 - drop everything and work on this (used only when _completely_ necessary)
- `priority-2` #1976D2 - high priority issue (what needs doing now)
- `priority-3` #42A5F5 - high priority (what needs doing next)
- `priority-4` #8DC9F9 - low priority (to be upgraded later)
- `priority-5` #C5DEF5 - lowest priority (non-urgent changes and backlog ideas)
- [`starter`](https://github.com/dwyl/labels/issues/36) #27AE60 - issues that those with not much coding experience can contribute to
- [`T[x]d`](https://github.com/dwyl/labels/issues/41) #F06292 - estimated time in 'x' days the issue will take to resolve
- [`T[x]h`](https://github.com/dwyl/labels/issues/41) #F7C6C7 - estimated time in 'x' hours the issue will take to resolve
- `technical` #D4C5F9 - technical tasks e.g. deployment
- [`user-feedback`](https://github.com/dwyl/labels/issues/61) #E91E63 - requests or features that have been added to the backlog as a direct result of user testing
- [`va-task`](https://github.com/dwyl/labels/issues/50) #128214 -
denotes administrative tasks that can be done by 'Virtual Assistants',
usually for [non-developers](https://www.amazon.co.uk/Virtual-Freedom-Chris-C-Ducker/dp/1939529743)

Github also gives you a pre-populated list of labels with every repo:

- `bug` #EE0701 - report a [bug](https://en.wikipedia.org/wiki/Software_bug), not to be confused with a request for additional changes to the code
- `duplicate` #CCCCCC - duplicate issue (link to duplicate in comments)
- `enhancement` #84B6EB - improving existing code
- `help-wanted` #128A0C - signals author of the issue is looking for help or expertise on a subject
_(NB. if you'd like to see where dwyl is in need of a helping hand, check out https://tudo-app.herokuapp.com/)_
- `invalid` #E6E6E6 - issue is not valid (not used in dwyl)
- `question` #CC317C - for open questions
- `wontfix` #ffffff - when an issue won't be addressed (add a comment to the issue as to *why* this is the case

**Comment by Oliversw** [comment]
After today's meeting we have discussed using:
- React
- Node (Express)
- MongoDB for database
- Jest for testing

**Comment by hshahwan** [comment]
what about 'styled component' for styling?

**Comment by Oliversw** [comment]
Kristina and I would be happy to learn more about styled components @hshahwan! What do you think @ali-7?

**Comment by ali-7** [comment]
yes, sure, we forget to talk about it in the meeting.

**Comment by teenie-quaggard** [comment]
Today Oliver and I spoke about using first a .json file to hold our data. This might be simpler than calling on a database as we have many other tasks to work on. Let's talk about this in standup on Monday.

**Comment by teenie-quaggard** [comment]
Closing this issue as we have decided for the meantime to:

Only make a front-end React app using a .json file to hold our content/data
