### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by charlielafosse** [founders-programme-2/commons#115]
Will probably be very simple/limited tests for the server

And will look into doing some component testing and snapshot testing :camera_flash: 

p.s let me know if the labels are correct! :sweat_smile:

**Comment by charlielafosse** [comment]
@Oliversw @hshahwan @ali-7 @teenie-quaggard it'd be good to have a discussion here about what we think are the most important things to test at this stage. Where does the most user interactivity happen? Where are things most likely to change in the UI?

**Comment by Oliversw** [comment]
Sorry, didn't see this until this morning @charlielafosse!! Did talking about it in person help yesterday or are you still wondering?

**Comment by charlielafosse** [comment]
Hey yeah our conversation did help! I've got a PR inbound... have a looky see what you think :sparkles:
