### ISSUE TITLE
Add to about commons page copy

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#144]
The bolded text should be added to the bottom: 

"About Commons 

This game will help you create a Commons - a set of places online and on the ground that provide an environment within which connections and collaboration can take place.

The are two ways that you can play Commons.

First you can play as a “community connector” using online methods and other activities to help people make connections, find opportunities in their community or network, and develop new projects and collaborations.

Second, you can play as a team reviewing the support that community connectors need, and consider how to develop a mapping, support and communication system. We call that team the hub, and their new system the community platform.

For more information on commons, hubs and platforms, see Key Terms. (https://commons-app.herokuapp.com/keyTerms)

**The app takes you through that process and helps you make choices. However, there are no “right” answers, and the app is best used stimulate your thinking, and discussion with others about a Commons. See Theory for more.**"

**Comment by socialreporter** [comment]
Thanks Oliver

My mistake, should be “used to stimulate”

In How to play I’ve added links to a wiki page where we will have materials download, how to play the workshop game.

I think we could also have  wiki link in Theory. Or should we rename Theory as resources? I’ll add this point in Quip

David
