### ISSUE TITLE
Can't click facebook on methods page

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#145]
![Screen Shot 2019-05-02 at 4 26 33 PM](https://user-images.githubusercontent.com/9094166/57087005-15cd2a80-6cf7-11e9-81d5-4260c184481a.png)

- I have a feeling that the breadcrumbs are getting in the way so this should hopefully be solved with Haneens work on the carousel

![Screen Shot 2019-05-02 at 4 27 08 PM](https://user-images.githubusercontent.com/9094166/57087054-27aecd80-6cf7-11e9-887b-5cd3aa3090c8.png)

**Comment by ali-7** [comment]
yes, "Paging dots" that name finally :joy:, it's in the way , with Hannen fix should be alright
