### ISSUE TITLE
Fix - issue where breadcrumbs overlap large cards

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/commons#153]
possibly remove them for now?

**Comment by ali-7** [comment]
@teenie-quaggard I think this happens in only one card, we can remove the only card for now, until maybe for the future another module that u can customize everything in it. 

`renderBottomCenterControls={null}` >> with them much better

**Comment by hshahwan** [comment]
no, I think those good for the player to inform him about multi-card, as Ali said we can delete the one that happened to it

can you explain more about that Ali 'renderBottomCenterControls={null}'?

**Comment by ali-7** [comment]
in mobile view, most of them overlap. 
`renderBottomCenterControls={null}`  remove them

**Comment by ali-7** [comment]
mmm, if there's no solution, I think to remove them for now, in mobile they're really awful. 
for desktop, just one card

**Comment by hshahwan** [comment]
Ok remove it 👩‍💻
