### ISSUE TITLE
Summary page visuals

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#24]
### User Story
As a user,  I want to be provided with a framework in which I can begin to imagine timelining the implementation of my chosen methods

### Acceptance Criteria
- [x] contains header
- [x] contains title
- [x] contains "Reprioritize" and "Tips for your action plan" buttons
- [x] contains timeline #68 
### Screenshots
![Screen Shot 2019-04-15 at 5 55 52 PM](https://user-images.githubusercontent.com/9094166/56150936-f53b6b80-5fa7-11e9-813b-161dbdc0aacc.png)
![Screen Shot 2019-04-15 at 5 56 09 PM](https://user-images.githubusercontent.com/9094166/56150938-f7052f00-5fa7-11e9-9031-f85feeede900.png)

**Comment by ali-7** [comment]
I think summary result data depends on the user choices and the plan he made, we need each choice (advice) data to present it.

**Comment by socialreporter** [comment]
Hi - have you been able to take a look at the pages I've developed on Quip - Commons screen index. I can discuss with Drew how we best handle choices and summary. Easiest for him if you can common on Quip, I think. Sorry to present you with all these design challenges. The good thing is you are making us think hard!

**Comment by Oliversw** [comment]
All part of the process @socialreporter! Thanks for having a look here and letting us know. I'll head over to Quip now to have a look!
