### ISSUE TITLE
Error Pages

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#26]
### Acceptance Criteria
- [x] contains logo
- [x] contains title
- [x] contains button (home?)

### Screenshots
![Screen Shot 2019-04-15 at 10 58 38 PM](https://user-images.githubusercontent.com/9094166/56168093-0ef1a880-5fd2-11e9-9cc5-b7420eacbd5a.png)

**Comment by teenie-quaggard** [comment]
@hshahwan @ali-7 
Just a note that I've only made the 404 page as we don't need a 500 atm.

I've put this back into TODO as we need to make a button component and decide where it brings user back to.

**Comment by ali-7** [comment]
@teenie-quaggard I made an issue for it #48
