### ISSUE TITLE
Carousel Component

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#33]
### Technical Component
** Need help defining acceptance criteria (see comment below)

### Screenshots
![Screen Shot 2019-04-16 at 10 46 48 AM](https://user-images.githubusercontent.com/9094166/56199568-1007f180-6035-11e9-8dcf-81f0b2f74153.png)
![Screen Shot 2019-04-16 at 10 46 53 AM](https://user-images.githubusercontent.com/9094166/56199569-1007f180-6035-11e9-93e7-a9e25b0e4cac.png)
![Screen Shot 2019-04-16 at 10 47 02 AM](https://user-images.githubusercontent.com/9094166/56199570-1007f180-6035-11e9-901a-d33cbc874cb5.png)

**Comment by Oliversw** [comment]
We have a number of carousels, which ideally could be a separate component. Personally I am slightly unsure of how best to implement this.
Would it take a component as a prop? That way we can create components for method cards, personas, and the small method cards and feed it into the carousel component. Thoughts?

**Comment by teenie-quaggard** [comment]
@founders-programme-2/commons 

I am keen to move forward on this in the quickest way possible. I have found this carousel from Formidable Labs. I will work on trying to implement it this afternoon and see how it goes. If I spend more than a couple of hours on it, it may be best to make our own. Let me know if you have any thoughts.

https://kenwheeler.github.io/nuka-carousel/#/
https://github.com/FormidableLabs/nuka-carousel
https://www.npmjs.com/package/nuka-carousel

**Comment by ali-7** [comment]
go for it :smiley:

**Comment by Oliversw** [comment]
Using the above module, which seems to work well! Closing this issue to avoid clutter.
