### ISSUE TITLE
Include navigation button and tagline on homepage

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#56]
### Acceptance Criteria
- [x] includes button to link to about page 
- [x] includes short tagline text

![Screen Shot 2019-04-21 at 3 21 23 PM](https://user-images.githubusercontent.com/9094166/56471347-42f12180-6449-11e9-93c6-920d6ce1b85a.png)

**Comment by ali-7** [comment]
relates #48 #58
