### ISSUE TITLE
1st User Testing Findings 

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/commons#8]
# Prototype User Testing Meeting with David
April 12, 2019

## Defining hub / platform / commons / networks
- We asked David to clearly define these terms as we were confused about the differences between them
- Since the app is called ‘Commons’ remove the word commons in explanations of ideas, replace it with hub

- **Hub**
    - *An organising group* that may have access to a physical space that fosters communication and collaboration 
    - An example might be a community center or a charity with an office

- **Platform**
    - A set of tools to help people work together - i.e. what we are trying to help people build by creating this web app.
    - "*A hub may want to develop a platform, to increase communication in their community*"

- **Commons**
    - A space (physical or otherwise) that is open to anyone

- **Network**
    - Groups of various organisations that work together for common causes
    - Often requires a membership
    - **Network mapping** makes these relationships visible and trackable

## Two potential routes for the game
- David spoke of two routes for the game
- We agreed to focus on the Commons route (related to a geographical area), with the potential to expand on the Networks route (more about networks of interest/causes) in the future

### Commons route
1. The goal of the game is to build a hub particular to a specific place (in his words, a locality - in our game, this is Slipham)
2. It includes personas - people that the user (implied to be a hub manager / developer) is trying to help. The personas give the user a problem to solve.
3. Specific **challenges** will also be associated with the personas
- This means that our scenario will have to somehow include all 3 sections. David and Drew will work on defining these.

### Networks route
1. The user here is implied to be a community connector
2. Here the user would be given the problem of connecting communities and so would have different set of problems to solve
3. This route is for support training / awareness raising 

## Background theory of game
- About page should include a short blurb on the background theory to the game. A longer version will be linked from there. This could also be linked in the hamburger menu.

## Methods
- Use the term 'methods' instead of 'tools' throughout the app
- Methods should be tagged with one or more of the following categories
    - **FINDING**
    - **SHARING**
    - **MANAGING**
    - **COLLABORATION**

## Main sequence
- David proposed a 'main sequence' for the flow of the app to follow, after reviewing our prototype:
    1. Choose and understand your scenario - the situation, and people you wish to support (scenario plus some personas)
    2. Review the challenges you wish to address - "How might we ...?", " "How can I ...?". (These can maybe be included on the scenario page. I think we will also need to find a way to refer back to them in the "Method Selection" pages)
    3. Choose the methods you will use
    4. Organise your toolkit and develop a plan ("Summary" page)
    5. Learn how to use your tools ("Summary" page should include links to how to use the various methods that have been selected)

**Comment by socialreporter** [comment]
Thanks Kristina - really helpful. I'll go through screens content too over the weekend to clarify

**Comment by teenie-quaggard** [comment]
Closing this issue now as most of these issues have been moved into their appropriate user journeys/stories
