### ISSUE TITLE
To Do on Figma

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#9]
After our discussion with David on Friday April 12. See #8 

- [x] include key terms definitions (commons, hub, platform, networks)
- [x] Since the app is called 'Commons' remove the word *commons* in explanations of ideas, replace it with hub
- [x] There will only be one scenerio - Slipham, but there will be **personas** and **challenges** to add in
    - [x] Scenerio page will need to be adapted to include a selection of personas / challenges
    - [x] There needs to be a way to refer back to the scenario page while selecting methods
- [x] Include background theory about game on the about page, with a link to an extended version somewhere out of the main flow
- [x] Categorise the methods with 'finding', 'sharing', 'managing' and/or 'collaboration' - Maybe the different categories can be represented by colors, like the ones currently on cards in the Figma. Not sure how to deal with multi-category methods though.
- [x] Include more 'leading' questions throughout the process to make the user thoughful about their decisions
- [x] Add in somewhere (probably hamburger menu) a link to print the workshop materials/cards for physical use. This will just be a pdf that will be put together at some point
- [ ] include scenario 'challenge' in summary?

**Comment by Oliversw** [comment]
@ali-7 @hshahwan Obviously we can all work on this but there are probably some things you can do on Sunday. If you have any questions about the user testing feedback or any of these points please just let us know! 🙂

**Comment by ali-7** [comment]
@Oliversw, @teenie-quaggard in which page this should be?
"include key terms definitions (commons, hub, platform, networks)" 
should include it on the menu?

**Comment by teenie-quaggard** [comment]
@founders-programme-2/commons  i've included a key terms page in the burger menu, but some of these terms, particularly commons and hub should be defined in the intro about page

**Comment by teenie-quaggard** [comment]
closing this issue, as we have incorporated most of these things into the Figma
