### ISSUE TITLE
Replace the over and under used resources warnings with Sweet Alert popups (methods)

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/commons#93]
- [x] Popup warning for remaining resources
- [x] Popup warning for no remaining resources
- [x] Old pages cleaned up and removed

**Comment by Oliversw** [comment]
We should maybe also include a warning for having no methods selected, and not let people move on without doing so, since not having methods messes up the priority screen

**Comment by ali-7** [comment]
@teenie-quaggard is this related to #71

**Comment by ali-7** [comment]
@Oliversw I think #98 solve it.
