### ISSUE TITLE
Check for existence of selected methods when loading '/priority-tools'

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#98]
Loading the page without any methods selected (or losing them when refreshing the page) prevents the 'Prioritize Your Tools' section from loading correctly. We need to check that there are selected methods already and either maybe prevent the page from loading if not, or include some kind of backup dummy data

![Screen Shot 2019-04-29 at 8 42 16 AM](https://user-images.githubusercontent.com/9094166/56882164-b94ddf00-6a5a-11e9-9c0b-5ebbd63ad3c1.png)

**Comment by ali-7** [comment]
if landing on this page, maybe put popup say that you need to select your methods and redirect to /methods
